language: ruby
rvm:
  - 2.1.4
script: bundle exec rake
before_install:
  - gem update --system
addons:
  code_climate:
    repo_token: c9feb70c5a955dd2ec8b0e1099992d45681fefcdaf72606e726e3cebe1d5c3fe
